version: '3.8'

services:
  homeassistant:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: homeassistant
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./config:/config
      - ./my-lovelace-card:/config/custom_components/my_lovelace_card
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=UTC
